services:
  # Backend Service (Django)
  - type: web
    name: safetnet-backend
    runtime: python
    plan: starter
    buildCommand: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      source venv/bin/activate
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: SafeTNet.settings
      - key: PYTHON_VERSION
        value: 3.13.0
      # DATABASE_URL should be automatically set when database is manually linked in Render dashboard
      # Or set it manually: Go to web service → Environment → Add DATABASE_URL from your database service
    autoDeploy: true
    healthCheckPath: /api/auth/test-auth/

